[package]
name = "hyper-example"
version = "0.1.0"
authors = ["divinerapier <poriter.coco@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.1.18"
hyper = "0.12"
futures = "0.1.29"
url = "2.1.0"
