[package]
name = "etcd-examples"
version = "0.1.0"
authors = ["sihao <sihao@momenta.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etcd = "*"
futures = "*"
tokio = "*"
